version: '3.3'
services:
  redis:
    container_name: zero-redis-node
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis/d–∞ta:/root/redis
    environment:
      - REDIS_PASSWORD=mszlu
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

# etcd
#version: "3.5"
#services:
#  Etcd:
#    container_name: etcd3-go-zero
#    image: bitnami/etcd:3.5.6
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_SNAPSHOT_COUNT=10000
#      - ETCD_QUOTA_BACKEND_BYTES=6442450944
#    privileged: true
#    volumes:
#      - ./volumes/etcd/data:/bitnami/etcd/data
#    ports:
#      - 2379:2379
#      - 2380:2380